variables:
 PROJECT_NAME: "proton-vpn-api-core"
 CARGO_HOME: $CI_PROJECT_DIR/.cargo

include:
 - project: 'ProtonVPN/Linux/integration/ci-libraries-rust'
   ref:  fc097803ecb19cb8a506446fd4e34176c4a19b48 # fix: [VPNLINUX-1899] Remove auth dialog
   file: 'develop-pipeline.yml'
