[package]
name = "proton-vpn-linux"
# TODO LT: Flip this back down to 0.x.x because the lib is not yet released, get .deb and rpms removed from repos
version = "0.5.0"
edition = "2021"

[features]
protun = ["dep:clap", "dep:zbus",
          "dep:shlex", "dep:glob", "sdk", "dep:rtnetlink", "dep:netlink-packet-route", "dep:futures",
          "nm_protun_auth_dialog"]
protun_fwmark = []
sdk = ["dep:protun", "dep:serde", "dep:serde_json", "dep:libc", "dep:base64", "dep:tokio",
       "dep:async-trait", "dep:rust-ini", "dep:serini"]
nm_protun_auth_dialog = ["dep:clap", "dep:oo7", "dep:tokio"]

core = ["dep:proton-vpn-binary-status", "dep:serde", "dep:serde_json"]
python = ["proton-vpn-binary-status/serde", "dep:pyo3", "dep:pythonize",
          "dep:pyo3-async-runtimes"]
local_agent = ["dep:serde", "dep:serde_json", "dep:async-trait",
               "dep:tokio-rustls", "dep:tokio", "dep:rustls-pki-types",
               "dep:bincode", "dep:rustls-pemfile", "dep:x509-parser", "dep:socket2"]

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "nm-protun-service"
required-features = ["protun"]

[[bin]]
name = "nm-protun-auth-dialog"
required-features = ["nm_protun_auth_dialog"]

[dependencies]
thiserror = "1.0.60"
log = "0.4.27"
env_logger = "0.11.5"
static_assertions = "1.1.0"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

# Core
proton-vpn-binary-status = { version="1", registry = "proton_public", optional=true }
tokio-rustls = { version="0.26.0", features = ["tls12"], optional=true }
rustls-pki-types = {version="1.7.0", optional=true }
bincode = {version="1.3.3", optional=true}
rustls-pemfile = {version="2.1.2", optional=true}
x509-parser = {version="0.16.0", optional=true}
socket2 = {version="0.5.7", features=["all"], optional=true}

# Protun
protun = { path="dependencies/protun", features = ["unix"], optional=true }
serde = {version = "1.0.228", features = ["derive"], optional=true}
serde_json = { version = "1.0.145", optional=true }
libc = { version ="0.2.178", optional=true }
base64 = { version="0.22.1", optional=true }
clap = { version="4.5.53", features=["derive"], optional=true }
oo7 = { version = "0.5", default-features = false, features = ["tokio", "native_crypto"], optional = true }
zbus = { version = "5", default-features = false, features = ["tokio"], optional = true }
rust-ini = { version = "0.21.3", optional = true }
shlex = { version = "1.3.0", optional = true }
glob = { version = "0.3.3", optional = true }
serini = { version="0.2.2", optional = true }
rtnetlink = { version = "0.14", optional = true }
netlink-packet-route = { version = "0.19", optional = true }
futures = { version = "0.3", optional = true }

# Protun/Core
async-trait = { version = "0.1", optional = true }
tokio = { version = "1", features = ["full"], optional = true }

# Python
pyo3 = {version="0.27", features = ["extension-module", "abi3-py38", "serde"], optional=true}
pyo3-async-runtimes = {version="0.27", features = ["attributes", "tokio-runtime"], optional=true}
pythonize = {version="0.27", optional=true}

[dev-dependencies]
test-log = "0.2.17"
