[package]
name = "proton-vpn-platform"
version = "5.6.7"
edition = "2021"

[features]
protun = ["dep:clap", "dep:zbus", "dep:zvariant",
          "dep:shlex", "dep:glob", "sdk", "dep:rtnetlink", "dep:netlink-packet-route", "dep:futures",
          "dep:nix",
          "nm_protun_auth_dialog"]

sdk = ["dep:protun", "dep:serde", "dep:serde_json", "dep:libc", "dep:base64", "dep:tokio",
       "dep:async-trait", "dep:rust-ini", "dep:serini"]
nm_protun_auth_dialog = ["dep:clap", "dep:oo7", "dep:tokio", "dep:libc"]

core = ["dep:proton-vpn-binary-status", "dep:serde", "dep:serde_json"]
kill_switch = ["dep:nftnl", "dep:mnl", "dep:ipnetwork", "dep:clap",
               "dep:zbus", "dep:zvariant", "dep:serde", "dep:tokio"]
python = ["proton-vpn-binary-status/serde", "dep:pyo3", "dep:pythonize",
          "dep:pyo3-async-runtimes"]
local_agent = ["dep:serde", "dep:serde_json", "dep:async-trait",
               "dep:tokio-rustls", "dep:tokio", "dep:rustls-pki-types",
               "dep:bincode", "dep:rustls-pemfile", "dep:x509-parser", "dep:socket2"]

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "nm-protun-service"
required-features = ["protun"]

[[bin]]
name = "nm-protun-auth-dialog"
required-features = ["nm_protun_auth_dialog"]

[[bin]]
name = "fwks"
required-features = ["kill_switch"]

[[bin]]
name = "proton-vpn-kill-switch-service"
required-features = ["kill_switch"]

[dependencies]
thiserror = "1.0.60"
log = "0.4.27"
env_logger = "0.11.5"
static_assertions = "1.1.0"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

# Core
proton-vpn-binary-status = { version="1", registry = "proton_public", optional=true }
tokio-rustls = { version="0.26.0", default-features = false, features = ["tls12", "ring"], optional=true }
rustls-pki-types = {version="1.7.0", optional=true }
bincode = {version="1.3.3", optional=true}
rustls-pemfile = {version="2.1.2", optional=true}
x509-parser = {version="0.16.0", optional=true}
socket2 = {version="0.5.7", features=["all"], optional=true}

# Protun
protun = { path="dependencies/protun", features = ["unix"], default-features = false, optional=true }
serde = {version = "1.0.228", features = ["derive"], optional=true}
serde_json = { version = "1.0.145", optional=true }
libc = { version ="0.2.178", optional=true }
base64 = { version="0.22.1", optional=true }
clap = { version="4.5.53", features=["derive"], optional=true }
oo7 = { version = "0.5", default-features = false, features = ["tokio", "native_crypto"], optional = true }
zbus = { version = "5", default-features = false, features = ["tokio"], optional = true }
zvariant = { version = "5", optional = true }
rust-ini = { version = "0.21.3", optional = true }
shlex = { version = "1.3.0", optional = true }
glob = { version = "0.3.3", optional = true }
serini = { version="0.2.2", optional = true }
rtnetlink = { version = "0.21", optional = true }
nix = { version = "0.27", features = ["user"], optional = true }
netlink-packet-route = { version = "0.30", optional = true }
futures = { version = "0.3", optional = true }

# Kill switch
nftnl = { version = "0.9.1", features = ["nftnl-1-2-0"], optional = true }
mnl = { version = "0.3.1", features = ["mnl-1-0-4"], optional = true }
ipnetwork = { version = "0.21.1", optional = true }

# Protun/Core
async-trait = { version = "0.1", optional = true }
tokio = { version = "1", features = ["full"], optional = true }

# Python
pyo3 = {version="0.28", features = ["extension-module", "abi3-py38", "serde"], optional=true}
pyo3-async-runtimes = {version="0.28", features = ["attributes", "tokio-runtime"], optional=true}
pythonize = {version="0.28", optional=true}

[dev-dependencies]
test-log = "0.2.17"
time = { version = "0.3.47", features = ["macros"] }

[[test]]
name = "agent_connection"
path = "tests/rust/agent_connection/main.rs"
