[package]
name = "python-proton-vpn-lib"
version = "1.0.1"
edition = "2021"

[lib]
crate-type   = ["cdylib"]

[dependencies]
proton-vpn-binary-status = { version="1", registry = "proton_public", features=["serde"] }
proton-vpn-lib-rs = { path = "../proton_vpn_lib_rs" }
pyo3 = {version="0.24.2", features = ["extension-module", "abi3-py38", "serde"]}
pyo3-async-runtimes = {version="0.24.0", features = ["attributes", "tokio-runtime"]}
tokio = { version = "1.38.0", features = ["full"] }
thiserror = "1.0.60"
log = "0.4.27"
env_logger = "0.11.5"
pythonize = "0.24.0"
